version: '3.8'

services:
  api:
    container_name:  "docker_api"
    # we want to use the image which is build from our Dockerfile
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app/

networks:
  default: